const providers = [
  {
    region: 'Languedoc-Rousillon',
    name: 'Cathala',
    image: 'cathala.jpg',
    description: 'Passionnés, nous avons créé en 2011 ; juste "pour le plaisir" cette gamme de vins avec pour objectif d’avoir une démarche qualitative, respectueuse des modes de cultures traditionnels et en phase avec la nature. Notre philosophie de vie « Amitié et Qualité ». Situé sur les pentes du parc Naturel des Cévennes et du Haut Languedoc, le domaine jouit d’une variété de sols riches argilo – calcaires mais aussi de schistes. Cette complémentarité de deux terroirs exceptionnels offre aux vins de belles nuances aromatiques. Nous avons organisé notre domaine sur une mixité Argilo-Calcaire & Schiste à 50/50 et cultivons les cépages Syrah, Grenache et Mourvèdre. On s’attache à préserver l’expression de cette rencontre géologique jusqu’à l’assemblage de nos cuvées. Il faut y voir le travail de passionnés ; on privilégie la qualité par le labour, les actions manuelles et on s’attache à un respect du raisin jusqu’au vendanges manuelles, tri et sélection des meilleurs grappes sur pieds lors de la cueillette. L’idée est de travailler beaucoup en vigne pour tâcher d’atteindre les conditions idéales pour faire des vins à concentration naturelle.   Nous produisons environ 22 à 25 000 bouteilles qui sont essentiellement diffusées en restaurants gastronomiques, sur une dizaine de tables étoilés, quelques professionnels respectueux de notre travail.\n',
    webSite: 'http://www.domaine-cathala.com/',
    bio: false,
    vegan: false,
  },
  {
    region: 'Jura',
    name: 'Lingot-Martin',
    image: 'lingotmartin.jpg',
    description: 'La Maison LINGOT-MARTIN implantée au cœur du vignoble Cerdonnais, est née en 1970 du regroupement de quatre familles. Attachés au terroir depuis plusieurs générations, nous avons su mettre en valeur 55 ha du vignoble de CERDON. Qualité des vignes, de leur environnement, des raisins, vendanges effectuées pour moitié à la main et à la machine, pressurage, vinification, mise en bouteilles, accueil clientèle, autant de postes de travail méticuleusement orchestrés.\n',
    webSite: 'http://www.lingot-martin.fr/',
    bio: false,
    vegan: false,
  },
  {
    region: 'Sud-Ouest',
    name: 'Brana',
    image: 'brana.jpg',
    description: 'Brana, une histoire de famille… Depuis plus d’un siècle, quatre générations se sont succédées dans le commerce du vin. En 1974, Etienne Brana et son épouse Adrienne créent la distillerie et plantent un verger de poiriers William. Etienne Brana se documente en Suisse et en Allemagne et découvre le circuit des vapeurs, la « Part des Anges » et construit, en empruntant, sa distillerie. Martine et Jean leurs enfants vont prendre le relais. Aujourd’hui Martine, distillatrice, a repris et développé le précieux savoir-faire ancestral familial et continue à innover avec les fruits, les épices et les plantes ! Toute la délicatesse et la finesse féminine se retrouvent à travers ces précieuses bouteilles de spiritueux. Jean en charge du vignoble Domaine Brana en A.O.P Irouléguy cultivé tout en terrasses. Soucieux du respect de la nature, ses pratiques sont écologiques et certifiées H.V.E (Haute Valeur Environnementale). L’histoire continue encore et toujours.\n',
    webSite: 'http://www.brana.fr',
    bio: false,
    vegan: false,
  },
  {
    region: 'Languedoc-Rousillon',
    name: 'A.C.L',
    image: 'acl.jpg',
    description: 'A.C.L, ce sont plusieurs Domaines (Vignerons indépendants), reconnus sur leurs appellations respectives,  qui se sont rapprochés commercialement, logistiquement et en terme de facturation, afin de pouvoir proposer à leurs clients une offre plus large des vins du Languedoc-Roussillon.\n',
    webSite: 'http://www.christophecoquema.com/pages/abbayes-et-chateaux-en-languedoc-acl.html',
    bio: false,
    vegan: false,
  },
  {
    region: 'Provence',
    name: 'Dalmeran',
    image: 'dalmeran.jpg',
    description: 'Au cœur des Baux de Provence, se niche le Domaine Dalmeran construit sur d’anciens vestiges gallo-romains, longé par l’ancienne voie Domitienne.  Une dizaine d’hectares plantés depuis un quart de siècle accueillent généreusement grenache, syrah, cabernet-sauvignon et cinsault sur une partie du versant nord des Alpilles.  On retrouve un microclimat sans cesse régénéré par le souffle puissant du mistral, la vigne s’épanouit pleinement dans un sol argilo-calcaire très caillouteux.  Les méthodes de culture sont traditionnelles et naturelles : pas d’engrais chimiques, ni de désherbants. Le domaine est en certification Bio depuis 2011. Le domaine produit un vin  Blanc , un vin rose et deux vins rouges , cuvée Bastide et cuvée Château.',
    webSite: 'http://www.dalmeran.fr/',
    bio: true,
    vegan: false,
  },
  {
    region: 'Rhône',
    name: 'Château Fontvert',
    image: 'fontvert.jpg',
    description: 'A quelques pas seulement du célèbre village provençal de Lourmarin, le vignoble de Château Fontvert s’étend sur les premiers contreforts du massif du Luberon. Le domaine, dont l’existence est attestée dès 1598, est depuis plus d’un demi-siècle la propriété de la famille Monod. En 1999, celle-ci décide de vinifier et d’élever elle-même les produits de son terroir, donnant ainsi naissance à la cave de Château Fontvert.\n',
    webSite: 'https://www.fontvert.com/',
    bio: true,
    vegan: false,
  },
  {
    region: 'Rhône',
    name: 'La Celestiere',
    image: 'celestiere.jpg',
    description: 'Situé au sud-ouest de l’appellation, La Celestiere a vu le jour en 2008 sous l’impulsion de Béatrice et Neil Joyce.  En agriculture biologique depuis 2013, le vignoble s’étend sur 26 hectares composé de différents sols : galets roulés, argilo calcaires et sablonneux… Outre les différentes cuvées de CHATEAUNEUF DU PAPE, cuvée tradition, cuvée La Croze et cuvée les Domaines , cette propriété  produit aussi un vin de Pays du VAUCLUSE et un COTES DU RHONE.   Les vendanges sont faites à la main et les raisins réceptionnés par gravité. Notre réputation pour faire des petits rendements, des vendanges assez tardives et des élevages longs, nous permet de proposer à nos clients des vins prêts à boire.\n',
    webSite: 'https://www.lacelestiere.fr/',
    bio: true,
    vegan: false,
  },
  {
    region: 'Bordeaux',
    name: 'Bretonniere',
    image: 'bretonniere.jpg',
    description: 'Vigneron Indépendant, passionné, perfectionniste et écologiquement responsable, je mets tout en œuvre pour que ces vins reflètent la meilleure expression de leurs terroirs et soient appréciés par tous. Entouré de spécialistes compétents (notamment un consultant en vin, ancien responsable d’un 1er Cru Classé de Pauillac pendant 25 ans) et avec beaucoup de générosité dans mon travail, je produis au Château ROMFORT des vins fruités qui combinent rondeur, caractère et longueur en bouche.\n',
    webSite: 'https://vignoblesheurlier.com/',
    bio: false,
    vegan: false,
  },
  {
    region: 'Sud-Ouest',
    name: 'Château Clamens',
    image: 'clamens.jpg',
    description: 'Nos 27 ha de vignes sont situées sur un terroir exceptionnel, aux portes de Toulouse : les sols limono-argilo-sablonneux des anciennes terrasses du Tarn (favorisant une bonne rétention de la chaleur) associés à un climat très favorable (plus de 2000 heures de soleil par an, nuits relativement fraîches, faible régime de pluie mais régulier).  Depuis maintenant 6 générations, nous cultivons la Négrette, un cépage local, qui apporte une typicité unique à nos vins : des arômes de fruits noirs, de réglisse, d’épices, … Des vins élégants, prêts à déguster, gourmands, charnus et des vins de garde, amples, puissants, riches et harmonieux.  Menée en lutte raisonnée, la vigne est conduite avec un objectif de maîtrise des rendements et de production axée sur la qualité (moins de 45hl par ha). Nombre de nos vignes sont plantées dans le sens du vent d’Autan pour réduire les traitements et assurer le meilleur état sanitaire possible. Ces attentions, de la vigne au chai, nous permettent de minimiser les doses de soufre dans les vins (aux alentours de 55 mg/l).\n',
    webSite: 'http://www.chateauclamens-fronton.com/',
    bio: false,
    vegan: false,
  },
  {
    region: 'Sud-Ouest',
    name: 'Dubard',
    image: 'dubard.jpg',
    description: 'L’Humain et la Terre. Il y a 40 ans, la famille Dubard a choisi une terre qu’ils n’ont jamais quittée. A partir de 2008, le domaine a connu un essor considérable avec l’arrivée de la deuxième génération, Gregory et Marine Dubard, ingénieurs-oenologues. Le vignoble s’est peu à peu étendu pour atteindre aujourd’hui près de 100ha sur la rive droite de la Dordogne : aux 85ha de la propriété historique en AOC Bergerac & Montravel sont venus s’ajouter 8.5ha de Lalande de Pomerol en 2008 puis 8.5ha de Puisseguin St Emilion en 2011.\n',
    webSite: 'http://www.vignoblesdubard.com/',
    bio: false,
    vegan: false,
  },
  {
    region: 'Loire',
    name: 'Eric Louis',
    image: 'eric.jpg',
    description: 'Domaine familial depuis 4 générations, notre vignoble de 33 hectares est enraciné au sud-est de l\'appellation Sancerre et est réparti sur 3 villages réputés pour leurs sols de silex : Thauvenay, Vinon et Ménétréol sous Sancerre. Notre Sauvignon et Pinot Noir poussent également sur des terroirs d\'argilo-calcaire. Cette atomisation parcellaire permet de jouer avec des vins issus de terroirs distincts. Nous produisons également d\'autres appellations satellites : Pouilly-Fumé, Menetou-Salon, Quincy ainsi que des vins de France en Sauvignon, Chardonnay, Pinot Noir... Toujours en quête de la haute précision, nous menons un travail minutieux et précis dans les vignes et en cave pour donner des vins "cousus mains".\n',
    webSite: 'http://www.sancerre-ericlouis.com',
    bio: false,
    vegan: false,
  },
  {
    region: 'Rhône',
    name: 'Les Favards',
    image: 'favards.jpg',
    description: 'L’histoire du Domaine des Favards : Casimir Barbaud a acheté la propriété en 1920. Comme tous les provençaux à l’époque il avait un surnom : Le Favard ! Comprenez le chanceux, celui qui a toujours la fève dans le gâteau des rois. Jean-Paul Barbaud et sa fille Céline sont la 3e et la 4e génération de Favards Vignerons. Ils produisent des vins d’appellation Côtes du Rhône et Plan de Dieu (Côtes du Rhône villages) dans le plus grand respect de la tradition et de leur terroir. Le domaine de 25 hectares est conduit en agriculture biologique.\n',
    webSite: 'https://www.favards.com/',
    bio: true,
    vegan: false,
  },
  {
    region: 'Languedoc-Rousillon',
    name: 'Saint Martin',
    image: 'saintmartin.jpg',
    description: 'Aujourd’hui, le domaine accueille la quatrième génération de vignerons, passionné dès sa jeunesse par le métier de vigneron, Henri a repris le flambeau du domaine familial en impulsant sa propre dynamique.Il a poursuivi le ré-encépagement du vignoble, et la modernisation de la cave afin de produire des vins de grande qualité, sur ce si beau terroir. Fier de son terroir, engagé auprès des femmes et des hommes de sa région, notamment avec le syndicat des Vins de Pays de la Cité de Carcassonne dont il est président, Henri souhaite « que demain ce territoire à la potentialité remarquable puisse continuer à accueillir de nouvelles générations de vignerons passionnés ».\n',
    webSite: 'https://www.domaine-saintmartin.fr/',
    bio: false,
    vegan: false,
  },
  {
    region: 'Bordeaux',
    name: 'Fleury Wines',
    image: 'fleury.jpg',
    description: 'Passionnée par les vins de Bordeaux depuis 1949, la famille Fleury possède une solide réputation d\'acteur exclusivement engagé au service de la qualité. Jean, actuel Président de FLEURY WINES, assure la continuité de l\'affaire familiale fondée par son père, Jean-Claude Fleury. L\'ambition de Fleury Wines est de : mettre en relation, au travers de leurs vins, des producteurs d’excellence et de vrais amateurs de qualité et être le garant de cette relation.  Détecter ces Grands Vins qui offrent une merveilleuse réplique aux Châteaux les plus prestigieux ; Les faire connaître, puis reconnaître. ',
    webSite: 'http://fleury-wines.com/',
    bio: true,
    vegan: false,
  },
  {
    region: 'Champagne',
    name: 'Champagne Mansard',
    image: 'mansard.jpg',
    description: 'Aujourd\'hui, notre vignoble s\'étend sur 24 ha de vignes répartis sur 10 communes avec plus de 66 parcelles.  Ce morcellement est un atout majeur qui se révèle bénéfique pour l\'assemblage de nos cuvées et pour la complexité et la fraîcheur de nos vins qui servent à élaborer un Champagne de longue garde.    Histoire familiale depuis 1901, la famille Mansard, propriétaire du Champagne Achille Princier a toujours été attachée aux valeurs fortes qui ont fait sa réputation : respect de la tradition, indépendance familiale, générosité. Dans cette famille, le vin est un art qui se transmet de la plantation des vignes jusqu\'à la commercialisation du Champagne. Dans ce cadre, l\'élaboration de vins provenant d\'un vignoble de 24 ha est un atout majeur pour la maison. Aujourd\'hui, notre vignoble s\'étend sur 24 ha de vignes répartis sur 10 communes avec plus de 66 parcelles.  Ce morcellement est un atout majeur qui se révèle bénéfique pour l\'assemblage de nos cuvées et pour la complexité et la fraîcheur de nos vins qui servent à élaborer un Champagne de longue garde.  Gilles Mansard transmet sa passion et son savoir-faire à ses fils, représentants de la cinquième génération. Dans notre propriété, au coeur de la Vallée de la Marne, située à quelques kilomètres d\'Epernay, nous élaborons nos Champagne à partir de 3 cépages : Pinot Noir, Pinot Meunier et Chardonnay, issus de notre vignoble.  L\'encépagement est composé de 65 % de Pinot Meunier, 10 % de Pinot Noir et 25 % de Chardonnay. Le Pinot Meunier nous apporte un bouquet intense et souvent très fruité, ainsi que de la rondeur aux assemblages. Le Pinot Noir apporte des bouquets aromatique de fruits rouges, par sa puissance et sa structure marquée. Et enfin, le Chardonnay se définit par une grande fraîcheur en bouche et contribue à l\'élégance et la finesse du Champagne. L\'âge du vignoble s\'étend de 7 à 84 ans dont 50 % de vignes de plus de 30 ans.\n',
    webSite: 'http://www.champagnemansard.com/fr/accueil/index.php',
    bio: false,
    vegan: false,
  },
  {
    region: 'Bourgogne',
    name: 'Louis Picamelot',
    image: 'picamelot.jpg',
    description: 'En 1926, Louis Picamelot a été l’un des premiers habitants de Rully à investir dans la production de “Bourgogne Mousseux”, élaboré par ce qu’on appelait alors dans ce temps-là, la Méthode Champenoise. De nos jours, nous l’appelons la Méthode Traditionnelle. Louis Picamelot a eu deux filles qui se sont mariées avec Jean-Baptiste Chautard (à gauche) et Louis Siraudin (à droite). Ils ont tous deux rejoint la Maison Louis Picamelot en 1949 et 1953. Philippe Chautard, second fils de Jean-Baptiste Chautard, a rejoint la maison en 1981 et en devint le dirigeant en 1987. En 2000, il fait l’acquisition de l’ancienne carrière du village (4000 m²) qui sera métamorphosée en une cuverie moderne, littéralement creusée dans la roche. Le toit végétal et les murs de pierres de l’ancienne carrière offrent une température naturellement contrôlée, ce qui s’inscrit alors dans une approche environnementale. Entre 2007 et 2011, afin d’assurer la maîtrise de la qualité de nos raisins, nous avons fait l’acquisition d’un peu plus de 10 hectares de vignes localisées en Côte Chalonnaise et en Côte de Beaune. En 2011, notre propre vignoble couvre 50% de nos besoins en raisins. Les 50% restant sont sélectionnés auprès de  vignerons fidèles et de confiance à travers toute la Bourgogne. D’où une large variété de terroirs au service de nos Crémants.\n',
    webSite: 'http://www.louispicamelot.com/fr/',
    bio: true,
    vegan: false,
  },
  {
    region: 'Champagne',
    name: 'Champagne Redempteur',
    image: 'redempteur.jpg',
    description: 'Passion et professionnalisme caractérisent la digne arrière petite-fille d\'une figure historique de la Champagne.   A la mémoire de notre ancêtre, nous restons une entreprise familiale et élaborons nos Champagnes dans le respect et la Tradition. Ainsi, toutes nos Cuvées sont élevées de 10 à 11 Mois en foudre de Chêne, et, le Remuage des bouteilles sur pupitre se fait chez nous, toujours à la main. C’est certainement l’attention et la passion de notre travail qui sont récompensées depuis plusieurs années par quelques distinctions et aussi des Médailles dans les Guides ou Revues Spécialisées. Et nous avons fêté avec grande fierté les 100 ans de la création de la Marque du Rédempteur, durant toute l’année 2011.\n',
    webSite: 'http://www.redempteur.com/fr/',
    bio: false,
    vegan: false,
  },
  {
    region: 'Rhône',
    name: 'Pierre Vidal',
    image: 'vidal.jpg',
    description: 'Formé sur les bancs et les terres bourguignonnes, Pierre Vidal, installé à Châteauneuf du Pape depuis 2010, est à l’image de ses vins, franc et direct ! Cet œnologue de formation, fin dégustateur, cherche à travers ses gammes à transmettre sa passion pour le bon vin, celui que l’on a envie de partager. C’est un touche à tout qui s\'implique à tous les stades de la création de ses cuvées. Dans une démarche écocitoyenne, tournée vers le respect de la nature et de ses partenaires vignerons, il vise ainsi à atteindre une harmonie parfaite entre terroir, climat, savoir-faire et temps pour élaborer de grands vins…',
    webSite: 'https://www.chateauneuf.com/pierre-vidal/',
    bio: true,
    vegan: true,
  },
  {
    region: 'Alsace',
    name: 'Scherb',
    image: 'scherb.jpg',
    description: 'Situé au coeur du vignoble alsacien et plus précisément dans la commune de GUEBERSCHWIHR,le Domaine Bernard SCHERB et Fils est un domaine familial que nous cultivons depuis 4 générations. Le vignoble alsacien s’étend sur 15000 hectares à l’Est de la France, au Nord-Est de la Bourgogne. En Alsace, nous produisons essentiellement des vins blancs aromatiques mais nous proposons également un vin rouge (le Pinot Noir). Notre Domaine cultive environ 15 hectares de vignes répartis sur une distance de 15kms appartenant à 4 communes différentes (Gueberschwihr, Voegtlinshoffen, Rouffach et Orschwihr). \n',
    webSite: 'http://www.scherb.fr/',
    bio: false,
    vegan: false,
  },
  {
    region: 'Champagne',
    name: 'Champagne Ambroise Laurent',
    image: 'ambroiselaurent.jpg',
    description: 'Nos vignes sont situées sur la côte des bars au cœur de la vallée de la seine. Notre vignoble se compose de 90 % de pinot noir et 10 % de chardonnay.  Une partie de la  vendange est vinifiée en fût. Assemblage de plusieurs années, quelquefois de plusieurs cépages. Beaucoup de dégustations, plusieurs années de repos en cave.\n',
    webSite: '',
    bio: false,
    vegan: false,
  }
];
export default providers;